import { useState } from 'react'
import {
  AlertTriangle,
  ArrowRight,
  Award,
  CalendarDays,
  Receipt,
  ShoppingCart,
  Sparkles,
  ThumbsDown,
  ThumbsUp,
  TrendingUp,
  Truck,
} from 'lucide-react'
import { Link } from 'react-router-dom'
import content from '../data/content-details.json'

const dash = content.pages.dashboard

function fmtRm(n: number) {
  return `RM ${n.toLocaleString('en-MY')}`
}

export function DashboardPage() {
  const briefing = dash.elements.find((e) => e.id === 'ai-daily-briefing')!
  const bc = briefing.content as {
    badge: string
    timestamp: string
    summary: string
    actions: { label: string; type: string; navigatesTo?: string }[]
  }

  const kpis = dash.elements.find((e) => e.id === 'kpi-row')!
  const kpiList = (kpis as { cards: {
    label: string
    value: string
    delta: string
    deltaType: string
    subtext: string
    icon: string
  }[] }).cards

  const tableEl = dash.elements.find((e) => e.id === 'outlet-performance-table')!

  const feedEl = dash.elements.find((e) => e.id === 'activity-feed')!

  const feed = feedEl.content as {
    items: {
      icon: string
      color: string
      title: string
      desc: string
    }[]
  }

  const table = tableEl.content as {
    title: string
    filter: { label: string }
    columns: { key: string; label: string; align?: string }[]
    rows: {
      outlet: string
      code: string
      region: string
      today: number
      mtd: number
      vsTarget: number
      topItem: string
      alerts: number
    }[]
  }

  const [range, setRange] = useState<'Today' | 'Week' | 'Month' | 'YTD'>('Week')

  const rowClass: Record<string, string> = {
    positive: 'row-c-green',
    warning: 'row-c-amber',
    accent: 'row-c-sky',
    primary: 'row-c-rose',
    inkMuted: 'row-c-mute',
  }

  const feedIcon = (name: string) => {
    switch (name) {
      case 'ShoppingCart':
        return <ShoppingCart size={16} strokeWidth={2} />
      case 'AlertTriangle':
        return <AlertTriangle size={16} strokeWidth={2} />
      case 'Receipt':
        return <Receipt size={16} strokeWidth={2} />
      case 'Award':
        return <Award size={16} strokeWidth={2} />
      case 'Truck':
        return <Truck size={16} strokeWidth={2} />
      default:
        return <ShoppingCart size={16} strokeWidth={2} />
    }
  }

  const kpiIcon = (name: string, tone: string) => {
    const c = tone as 'tone-green' | 'tone-sky' | 'tone-violet' | 'tone-mint' | 'tone-amber'
    const ic =
      name === 'TrendingUp' ? (
        <TrendingUp size={18} strokeWidth={2} />
      ) : name === 'ShoppingCart' ? (
        <ShoppingCart size={18} strokeWidth={2} />
      ) : name === 'Store' ? (
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="m2 7 1-4h18l1 4M3 7v13h18V7M8 12h8" />
        </svg>
      ) : name === 'CalendarDays' ? (
        <CalendarDays size={18} strokeWidth={2} />
      ) : (
        <AlertTriangle size={18} strokeWidth={2} />
      )
    return { c, ic }
  }

  const toneForKpi = (i: number): 'tone-green' | 'tone-sky' | 'tone-violet' | 'tone-mint' | 'tone-amber' =>
    ([
      'tone-green',
      'tone-sky',
      'tone-violet',
      'tone-mint',
      'tone-amber',
    ][i] as 'tone-green' | 'tone-sky' | 'tone-violet' | 'tone-mint' | 'tone-amber' | undefined) ??
    'tone-amber'

  return (
    <>
      <section className="page-head reveal">
        <div>
          <h1>Good morning, Sarah.</h1>
          <p className="sub">
            Here&apos;s the floor · Mid Valley · 28 Apr 2026 · <b>Open</b> for service · 3 staff on
            shift
          </p>
        </div>
        <div className="range-tabs">
          {(['Today', 'Week', 'Month', 'YTD'] as const).map((r) => (
            <button key={r} type="button" className={range === r ? 'on' : ''} onClick={() => setRange(r)}>
              {r}
            </button>
          ))}
        </div>
      </section>

      <div className="content">
        <section className="briefing reveal d1">
          <div>
            <div className="briefing-head">
              <div className="briefing-icon">
                <Sparkles size={18} strokeWidth={2} />
              </div>
              <div className="briefing-meta">
                <span className="briefing-tag">{bc.badge}</span>
                <span className="briefing-time">
                  {bc.timestamp?.split('·')[0]?.trim() ?? '7:00 AM'} · Generated by gpt-flora-4{' '}
                  <span className="conf">● Conf 78%</span>
                </span>
              </div>
            </div>
            <p>{bc.summary}</p>
            <div className="briefing-actions">
              <Link to="/inventory" className="btn btn-primary">
                Review 1 Utama <ArrowRight size={14} strokeWidth={2} />
              </Link>
              <Link to="/ai-bi" className="btn btn-ghost">
                See full insights
              </Link>
            </div>
          </div>
          <div className="briefing-feedback">
            <span className="label">Was this useful?</span>
            <div className="thumbs">
              <button type="button" aria-label="Helpful">
                <ThumbsUp size={14} strokeWidth={2} />
              </button>
              <button type="button" aria-label="Not helpful">
                <ThumbsDown size={14} strokeWidth={2} />
              </button>
            </div>
          </div>
        </section>

        <section className="kpis reveal d2">
          {kpiList.map((card, i) => {
            const { c, ic } = kpiIcon(card.icon, toneForKpi(i))
            const warn = card.deltaType === 'warning'
            return (
              <article key={card.label} className={`kpi ${c}`}>
                <div className="kpi-head">
                  <div className="kpi-icon">{ic}</div>
                  <span className="kpi-label">{card.label}</span>
                </div>
                <div className="kpi-value">
                  {card.value.startsWith('RM') ? (
                    <>
                      <span className="unit">RM</span>
                      {card.value.replace(/^RM\s?/, '')}
                    </>
                  ) : card.value.includes('/') ? (
                    <>
                      {card.value.split('/')[0].trim()}
                      <span style={{ fontSize: 22, color: 'var(--ink-3)', fontWeight: 500 }}>
                        {' '}
                        / {card.value.split('/')[1].trim()}
                      </span>
                    </>
                  ) : (
                    card.value
                  )}
                </div>
                <div className="kpi-foot">
                  <span className={`kpi-delta ${warn ? 'warn' : 'up'}`}>
                    {warn ? '' : '▲ '}
                    {card.delta}
                  </span>
                  <span className="kpi-sub">{card.subtext}</span>
                </div>
                {i !== 2 ? (
                  <svg className="kpi-spark" viewBox="0 0 110 50" preserveAspectRatio="none" aria-hidden>
                    <polyline
                      fill="none"
                      stroke={
                        i === 0
                          ? 'var(--green)'
                          : i === 1
                            ? 'var(--tone-sky)'
                            : i === 3
                              ? 'var(--tone-mint)'
                              : 'var(--tone-amber)'
                      }
                      strokeWidth="2"
                      points={
                        i === 0
                          ? '0,38 12,32 24,34 36,28 48,30 60,22 72,24 84,16 96,18 110,8'
                          : i === 1
                            ? '0,40 14,36 28,30 42,34 56,24 70,26 84,18 98,20 110,12'
                            : i === 3
                              ? '0,44 10,42 22,38 34,34 46,36 56,28 68,26 78,22 92,14 105,18 110,10'
                              : i === 4
                                ? '0,36 14,38 26,42 38,46 52,42 62,46 74,42 96,46 105,42 110,44'
                              : '0,42 12,40 24,38 36,36 48,32 60,30 72,26 84,22 96,18 110,12'
                      }
                    />
                  </svg>
                ) : null}
              </article>
            )
          })}
        </section>

        <section className="mid">
          <article className="panel reveal d3">
            <div className="panel-head">
              <div>
                <div className="panel-title">
                  Sales Trend <span className="badge tag">30D</span>
                </div>
                <div className="panel-sub">All outlets combined · Updated 14:23</div>
              </div>
              <span className="badge up">▲ +14.3% MoM</span>
            </div>
            <div className="chart">
              <svg viewBox="0 0 700 220" preserveAspectRatio="xMidYMid meet" aria-label="Sales trend chart">
                <defs>
                  <linearGradient id="areaFill" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="var(--green)" stopOpacity="0.55" />
                    <stop offset="55%" stopColor="var(--green)" stopOpacity="0.1" />
                    <stop offset="100%" stopColor="var(--green)" stopOpacity="0" />
                  </linearGradient>
                  <linearGradient id="lineGrad" x1="0" y1="0" x2="1" y2="0">
                    <stop offset="0%" stopColor="var(--green)" />
                    <stop offset="100%" stopColor="var(--tone-mint)" />
                  </linearGradient>
                </defs>
                <g stroke="var(--line-subtle)" strokeWidth="1">
                  <line x1="0" y1="40" x2="700" y2="40" />
                  <line x1="0" y1="100" x2="700" y2="100" />
                  <line x1="0" y1="160" x2="700" y2="160" />
                  <line x1="0" y1="210" x2="700" y2="210" />
                </g>
                <g fill="var(--ink-4)" fontFamily="JetBrains Mono" fontSize="9" letterSpacing="0.5">
                  <text x="6" y="36">
                    RM 18K
                  </text>
                  <text x="6" y="96">
                    RM 12K
                  </text>
                  <text x="6" y="156">
                    RM 6K
                  </text>
                </g>
                <path
                  d="M 0,170 L 24,160 48,164 72,150 96,156 120,142 144,138 168,128 192,134 216,118 240,112 264,108 288,118 312,96 336,102 360,82 384,90 408,72 432,76 456,62 480,68 504,54 528,58 552,42 576,48 600,38 624,44 648,30 672,36 700,28 L 700,220 L 0,220 Z"
                  fill="url(#areaFill)"
                />
                <path
                  d="M 0,170 L 24,160 48,164 72,150 96,156 120,142 144,138 168,128 192,134 216,118 240,112 264,108 288,118 312,96 336,102 360,82 384,90 408,72 432,76 456,62 480,68 504,54 528,58 552,42 576,48 600,38 624,44 648,30 672,36 700,28"
                  fill="none"
                  stroke="url(#lineGrad)"
                  strokeWidth="2.4"
                  strokeLinejoin="round"
                  strokeLinecap="round"
                />
                <circle cx="700" cy="28" r="4.5" fill="var(--green)" />
                <g fill="var(--ink-4)" fontFamily="JetBrains Mono" fontSize="9" letterSpacing="0.6">
                  <text x="0" y="218">
                    29 Mar
                  </text>
                  <text x="160" y="218">
                    5 Apr
                  </text>
                  <text x="320" y="218">
                    12 Apr
                  </text>
                  <text x="480" y="218">
                    19 Apr
                  </text>
                  <text x="640" y="218">
                    28 Apr
                  </text>
                </g>
              </svg>
            </div>
            <div className="chart-stats">
              <div className="chart-stat">
                <div className="lbl">Today</div>
                <div className="val">
                  RM 13.3K <small>+8.2%</small>
                </div>
              </div>
              <div className="chart-stat">
                <div className="lbl">7-day Avg</div>
                <div className="val">RM 12.1K</div>
              </div>
              <div className="chart-stat">
                <div className="lbl">MTD</div>
                <div className="val">
                  RM 409.1K <small>+14.3%</small>
                </div>
              </div>
              <div className="chart-stat">
                <div className="lbl">Forecast (next 7d)</div>
                <div className="val">
                  RM 41.5K <small>± 6%</small>
                </div>
              </div>
            </div>
          </article>

          <article className="panel reveal d4">
            <div className="panel-head">
              <div>
                <div className="panel-title">
                  <span className="live-dot" /> Activity Feed
                </div>
                <div className="panel-sub">Across all outlets · auto-refresh</div>
              </div>
              <span className="badge live">● LIVE</span>
            </div>
            <ul className="feed">
              {feed.items.map((item) => (
                <li key={item.title} className={rowClass[item.color] ?? 'row-c-mute'}>
                  <div className="feed-icon">{feedIcon(item.icon)}</div>
                  <div className="feed-body">
                    <div className="feed-title">{item.title}</div>
                    <div className="feed-desc">{item.desc}</div>
                  </div>
                  <div className="feed-time">
                    {[...item.desc.matchAll(/\d{2}:\d{2}/g)].pop()?.[0] ?? ''}
                  </div>
                </li>
              ))}
            </ul>
          </article>
        </section>

        <article className="panel reveal d5">
          <div className="outlets-head">
            <div>
              <div className="panel-title">
                Outlet Performance <span className="badge tag">This Month</span>
              </div>
              <div className="panel-sub">Click any row to drill into outlet detail</div>
            </div>
            <button type="button" className="filter-pill">
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <polygon points="22 3 2 3 10 12.5 10 19 14 21 14 12.5 22 3" />
              </svg>
              {table.filter.label}
            </button>
          </div>
          <div style={{ overflowX: 'auto' }}>
            <table className="outlets">
              <thead>
                <tr>
                  <th>Outlet</th>
                  <th className="r">Today</th>
                  <th className="r">MTD</th>
                  <th className="r">vs. Target</th>
                  <th>Top Item</th>
                  <th className="c">Alerts</th>
                  <th className="r" />
                </tr>
              </thead>
              <tbody>
                {table.rows.map((row) => {
                  const markClass = row.code === 'KLS' ? 'kls' : row.code === 'MV' ? 'mv' : 'u1'
                  const up = row.vsTarget >= 100
                  const alertCls =
                    row.alerts === 0 ? 'zero' : row.alerts <= 1 ? 'low' : 'high'
                  const skuSold =
                    row.outlet === 'KL Sentral'
                      ? 'CP-001 · 89 sold'
                      : row.outlet === 'Mid Valley'
                        ? 'MB-002 · 134 sold'
                        : 'CP-002 · 47 sold'
                  return (
                    <tr key={row.code}>
                      <td className="lead">
                        <div className="outlet-cell">
                          <div className={`outlet-mark ${markClass}`}>
                            <span>{row.code}</span>
                          </div>
                          <div>
                            <div className="outlet-name">
                              {row.outlet}
                              {row.code === 'MV' ? (
                                <span
                                  style={{
                                    color: 'var(--green)',
                                    fontSize: 10,
                                    letterSpacing: 1.4,
                                    textTransform: 'uppercase',
                                    fontWeight: 700,
                                    marginLeft: 6,
                                  }}
                                >
                                  ★ Yours
                                </span>
                              ) : null}
                            </div>
                            <div className="outlet-region">
                              {row.region.toUpperCase()} · {row.code}
                            </div>
                          </div>
                        </div>
                      </td>
                      <td className="r">{fmtRm(row.today)}</td>
                      <td className="r">{fmtRm(row.mtd)}</td>
                      <td className="r">
                        <div className="target-meter">
                          <span className={`target-pct ${up ? 'up' : 'dn'}`}>{row.vsTarget}%</span>
                          <span className="target-bar">
                            <i
                              className={up ? '' : 'dn'}
                              style={{ width: `${Math.min(row.vsTarget, 100)}%` }}
                            />
                          </span>
                        </div>
                      </td>
                      <td>
                        <div className="top-item">
                          {row.topItem}
                          <small>{skuSold}</small>
                        </div>
                      </td>
                      <td className="c">
                        <span className={`alert-pill ${alertCls}`}>{row.alerts}</span>
                      </td>
                      <td className="r">
                        <span className="chev">
                          <ArrowRight size={14} strokeWidth={2} />
                        </span>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
          <div className="signoff" style={{ padding: '16px 24px' }}>
            <div className="dot-row">
              <span className="d" /> Live · Last sync 14:23 MYT
            </div>
            <div>
              Network total ·{' '}
              <strong style={{ color: 'var(--ink-1)', fontFamily: 'var(--font-mono)' }}>RM 409,100</strong> MTD across
              3 outlets
            </div>
          </div>
        </article>

        <div className="signoff">
          <div className="dot-row">
            <span className="d" /> Franchise OS v3.2 · Encore-aligned UI
          </div>
          <div>© 2026 · Mid Valley Cafe SDN BHD</div>
        </div>
      </div>
    </>
  )
}
